server:
  port: 8080
spring:
  application:
    name: service-a
  config:
    import: "optional:configserver:http://localhost:8888/"
  profiles:
    active:
      - prod

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true

info:
  application:
    name: "Service A"
    description: "SpringBootServiceDiscovery Project's Service-A"
  organization: "Android 22"